"""empty message

Revision ID: 328559e660f0
Revises: cbfa3506e505
Create Date: 2025-05-26 15:17:22.495405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '328559e660f0'
down_revision: Union[str, None] = 'cbfa3506e505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_support_message', sa.DateTime(), nullable=True))
    op.drop_column('users', 'support_limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('support_limit', sa.BOOLEAN(), nullable=False))
    op.drop_column('users', 'last_support_message')
    # ### end Alembic commands ###
