"""empty message

Revision ID: 3e68c2f9f557
Revises: 403f690b50d1
Create Date: 2025-05-25 19:19:31.858980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e68c2f9f557'
down_revision: Union[str, None] = '403f690b50d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('limit_queries', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('date_end_subscription', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_end_subscription')
    op.drop_column('subscriptions', 'limit_queries')
    # ### end Alembic commands ###
