"""empty message

Revision ID: cbfa3506e505
Revises: 3e68c2f9f557
Create Date: 2025-05-26 13:18:12.524774

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cbfa3506e505"
down_revision: Union[str, None] = "3e68c2f9f557"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("partner_id", sa.Integer(), nullable=True))
    op.alter_column("users", "language", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "language", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("users", "partner_id")
    # ### end Alembic commands ###
