"""empty message

Revision ID: dedd1dd9d1b9
Revises: 3e68c2f9f557
Create Date: 2025-05-25 23:36:10.864447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dedd1dd9d1b9'
down_revision: Union[str, None] = '3e68c2f9f557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
